### ISSUE TITLE
Indicator coverage: coverage data export

### ISSUE THREAD

**Issue by pindec** [open-contracting/cove-oc4ids#102]
Child issue of #95

We could provide an XSLX/CSV export of the indicator coverage data and the missing fields data. See [example](https://docs.google.com/spreadsheets/d/1KRrW4mD5qJX7JT5RtH8DJw9rNUV6M3rnDS3WbZvB31s/edit#gid=312838369).

Indicator coverage:
 
topic | question | indicator | measurable | indicator_coverage
-- | -- | -- | -- | --
efficiency | Are there significant cost overruns? | Proportion of projects with final value > budget | TRUE | 9.27%

Missing fields:
topic | question | indicator | missing_fields | missing_fields_coverage
-- | -- | -- | -- | --
efficiency | Are there significant cost overruns? | Proportion of projects with final value > budget | budget/amount/amount, budget/amount/currency | 90.64%

They can't easily be in the same sheet without repetition because for each indicator, there might be multiple different sets of fields in `missing_fields`

We shouldn't use the colours since it's not clear for all contexts what 'good/green' or 'intermediate/yellow' coverage percentages might be.

We should provide an explanation of each coverage statistic to aid interpretability outside the DRT context.

**Comment by jpmckinney** [comment]
The numbers should always be "higher is better". It seems like "missing_fields_coverage" answers "how often is this field missing?", which is the opposite of the other table.

**Comment by jpmckinney** [comment]
Closing as not planned, as demand has not been validated by users. Web report seems sufficient #103.
