### ISSUE TITLE
502 Bad Gateway Error / Internal Server Error 

### ISSUE THREAD

**Issue by duncandewhurst** [open-contracting/cove-oc4ids#105]
I tried to upload [this file](https://drive.google.com/file/d/1mKOry3HlItxvEEmxC_nPiHwjNI1V8-4c/view?usp=sharing) from CoST Ukraine to demo the new field coverage visualisation feature.

On the first attempt, the DRT showed the loading icon for a while and then returned an unstyled 502 Bad Gateway Error.

On the second and third attempts, the DRT showed the loading icon for a while and then returned an internal server error:

![image](https://user-images.githubusercontent.com/19265814/132416770-2fb141b4-c3c8-4acf-9b7f-b6c32ff21d05.png)

The DRT can load the sample data and testing with an older version of CoST Ukraine's data [works OK](https://standard.open-contracting.org/infrastructure/review/data/bc31f277-d214-4a75-8b20-fe4dabdba31c).

I tried using the `libcoveoc4ids` CLI in a colab notebook and it processed the file successfully in 46s.

Edit: the new file issue has ~17k projects and the older file has ~10k projects

**Comment by Bjwebb** [comment]
Yes, I this is due to running out of memory on the server. I think it's only just too much memory, which is why a small change in the file could have pushed it over the edge. We're currently using the smallest possible Bytemark box, so we should be able to fix this by increasing that to the next size up. @jpmckinney Are you happy for me to increase the server size?

**Comment by yolile** [comment]
@Bjwebb James is on vacation this week, I would say yes to increasing the server specs, but if this is not urgent we could wait for James to also approve next week.

**Comment by duncandewhurst** [comment]
Thanks, both. Only CoST Ukraine has this much data and as far as I'm aware they aren't actively using the tool right now, so I think it can wait until next week.

**Comment by jpmckinney** [comment]
I've added 1GB (now 2GB total). The server is restarting. Only @dogsbody or OCP should make changes to server resources.

Bytemark has no user management, so I don't remember which users have access to the account. What username is ODS using to access OCP servers?

**Comment by duncandewhurst** [comment]
Hmmm, it still errored when I tried it with the CoST Ukraine data linked above: https://standard.open-contracting.org/infrastructure/review/data/5aa8041b-fe04-48e9-adad-6b04bd4deb99

**Comment by Bjwebb** [comment]
> Bytemark has no user management, so I don't remember which users have access to the account. What username is ODS using to access OCP servers?

I'm using the "opendataservices" username.

**Comment by Bjwebb** [comment]
@duncandewhurst There's a uwsgi limit which we also need to increase. I can do it tomorrow when I'm back at my desktop.

**Comment by jpmckinney** [comment]
I'm re-deploying the server to change the uWSGI memory limit.

**Comment by jpmckinney** [comment]
Got the error again on 2GB. Scaling and deploying with 3GB now.

**Comment by jpmckinney** [comment]
Got the error again on 2GB. Scaling and deploying with 3GB now. Seems to work: https://standard.open-contracting.org/infrastructure/review/data/6bafdb59-d483-4f40-bcf5-9fb1c6a1f1af

**Comment by duncandewhurst** [comment]
Great, thanks both!
