### ISSUE TITLE
DRT update to allow 3 digits for version

### ISSUE THREAD

**Issue by odscrachel** [open-contracting/cove-oc4ids#107]
I've just noticed that DRT doesn't accept 0.9.3 as the new version as the regex expects only 2 digits, you can see an example here https://standard.open-contracting.org/infrastructure/review/data/5ffe4b0a-93d7-4a98-80fb-db563fc549b7

**Comment by jpmckinney** [comment]
I think that's deliberate. In OCDS (and I'm pretty sure in OC4IDS), only the minor version (0.9) is specified.

**Comment by odscrachel** [comment]
Ah, we don't include patch, I'll close this
