### ISSUE TITLE
Remaining tweaks to cove instance after sprint 1

### ISSUE THREAD

**Issue by michaelwood** [open-contracting/cove-oc4ids#29]
Via @jpmckinney:
 * [ ] Decrease the font size of the headers (at least to fit OC4IDS on one line)
 * [ ] Swap the positions of the "Check and review" and "About OC4IDS" blocks (ideally, "About OC4IDS" would come after both blocks, as it's the least relevant content)
 * [ ] The hyperlinks in the footer do not have a clearly distinct color from text
 * [ ] The form prompts can be improved so that a first time user knows what to do without scrolling below the fold to read the instructions, e.g. "Upload an OC4IDS project package" instead of simply "Upload". I'm not including a full review here.
 * [ ] "… is missing but required within releases" is repeated for different indices within an array, instead of collected into one row.

**Comment by jpmckinney** [comment]
* We can remove #14 from the issue description as it's now closed
* We can remove the sub-bullets about OCDS, as I've opened separate issues for those
* The "First 3 Examples" bullet is now at https://github.com/OpenDataServices/cove/issues/1198 as it's a general CoVE issue.

**Comment by duncandewhurst** [comment]
I've updated the issue description.

**Comment by jpmckinney** [comment]
Such tweaks are already covered by the new wireframes for the next DRT TOR (not yet advertised), so this issue is obsolete.
