### ISSUE TITLE
Additional commits on merged branches

### ISSUE THREAD

**Issue by jpmckinney** [open-contracting/cove-oc4ids#34]
@michaelwood I see that there are two merged branches, with additional unmerged commits. Can you delete the branches, or create new issues/PRs if the new commits ought to be merged?

**Comment by michaelwood** [comment]
I can safely delete those branches as the "unmerged commits"  actually are in the master branch but github doesn't have a way to track commits which have been added by rebasing on top of the master branch (as opposed to a merged branch for instance) so incorrectly marks them as ahead by x commits.
