### ISSUE TITLE
Move OCP logo to footer, using new logo

### ISSUE THREAD

**Issue by jpmckinney** [open-contracting/cove-oc4ids#37]
![OC_logo_RGB_grey](https://user-images.githubusercontent.com/26463/68507540-262c0800-023a-11ea-96fc-6297cb55dee7.png)

**Comment by jpmckinney** [comment]
Same as https://github.com/OpenDataServices/cove/issues/1245

**Comment by robredpath** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Move OCP logo to footer + use new logo](https://trello.com/c/qSRe3mn0/75-move-ocp-logo-to-footer-use-new-logo)

**Comment by jpmckinney** [comment]
This is covered by the new wireframes, to be published as part of TOR.
