### ISSUE TITLE
Switch to GitHub Actions

### ISSUE THREAD

**Issue by jpmckinney** [open-contracting/cove-oc4ids#43]

**Comment by robredpath** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Quick fixes for large files](https://trello.com/c/pZJldiNG/70-quick-fixes-for-large-files)

**Comment by odscjames** [comment]
This one is having problems; coverage command fails

```
selenium.common.exceptions.WebDriverException: Message: unknown error: Chrome failed to start: exited abnormally.
  (unknown error: DevToolsActivePort file doesn't exist)
  (The process started from chrome location /usr/bin/google-chrome is no longer running, so ChromeDriver is assuming that Chrome has crashed.)
```

Tried:

- Manually starting chrome, like old Travis file did
- From https://github.com/actions/virtual-environments/issues/506, manually installing selenium (not needed, already there)
- From https://github.com/actions/virtual-environments/issues/506 , the manual test getting GitHub's page title - it works
- Running without coverage command, to see if rest worked. The other pytest command also fails with same error.
- Running coverage command locally - ran first time, no fancy setup needed, edited test and saw it fail too

Weird thing is it's basically a copy and paste from the normal cove repo, and I'm pretty sure Selenium runs fine on that one. I tested it failing by editing a test to have bad expected results.

**Comment by odscjames** [comment]
Ok, after trying more things worked out it's one specific test that fails, and that test was run by both commands. After looking into the reason the test was introduced and what it did, I think it's safe to remove it as other tests cover this anyway.
