### ISSUE TITLE
Report blank and empty fields

### ISSUE THREAD

**Issue by duncandewhurst** [open-contracting/cove-oc4ids#45]
Issue present in draft data shared by a publisher but not reported in the DRT

**Comment by duncandewhurst** [comment]
We can reuse the check and text from the OCDS DRT:

![image](https://user-images.githubusercontent.com/19265814/93540488-eda3a180-f9a7-11ea-9380-d8df2b31ac5a.png)

**Comment by michaelwood** [comment]
_note for self_ `cove_ocds/templates/cove_ocds/additional_checks_table.html`
