### ISSUE TITLE
Report duplicate items in arrays

### ISSUE THREAD

**Issue by duncandewhurst** [open-contracting/cove-oc4ids#49]
Issue present in draft data shared by a publisher but not reported in the DRT.

**Comment by jpmckinney** [comment]
Which arrays? Does the schema specify `uniqueItems` on those arrays?

**Comment by duncandewhurst** [comment]
> Does the schema specify `uniqueItems` on those arrays?

At the time of writing it didn't, but since 0.9.2 `uniqueItems` is set on all arrays except `Location/geometry/coordinates`, so this is no longer required as an additional check.

For the record, the array which prompted the issue was `contractingProcesses/summary/modifications`
