### ISSUE TITLE
Add a command-line interface to support local processing of large files

### ISSUE THREAD

**Issue by duncandewhurst** [open-contracting/cove-oc4ids#55]
Some files shared with the helpdesk are too large to process in the web interface

OCDS Kit's `validate` command can be used for basic schema validation of local files, but it would be good to make the full suite of checks in the DRT available on the command-line.

**Comment by jpmckinney** [comment]
I noticed a few memory errors :) We can resize the server (we kept it small until now because this was never an issue).

How large is the file you are uploading in MB?

**Comment by duncandewhurst** [comment]
Ah, good. It's 37mb

**Comment by jpmckinney** [comment]
@duncandewhurst I resized it from 1GB RAM to 2GB RAM. Can you try and see?

https://standard.open-contracting.org/infrastructure/review/

**Comment by duncandewhurst** [comment]
It hasn't errored but it's still loading after nearly 2 hours!

In any case, in the absence of Kingfisher-process support for OC4IDS it would be useful to have a means to get a machine-readable list of issues for a whole dataset so we can summarise them for feedback to publishers.

Validating the file with the OC4IDS schema using OCDS Kit results in >5,000 errors, but the output is difficult to filter/summarise.

**Comment by jpmckinney** [comment]
Hmm, well at least the sample data responds immediately.

Can you try again? I'm not seeing any Sentry or Prometheus alerts, so without looking deeper, I'm not sure what could have happened.

**Comment by jpmckinney** [comment]
Is it the data in CRM-6110?

**Comment by jpmckinney** [comment]
I tried with the file, and the server exceeded CPU and memory limits. CoVE really shouldn't choke on such small files.

**Comment by odscjames** [comment]
https://github.com/open-contracting/lib-cove-oc4ids has a command line interface already.

So I'd argue not to add this to the actual Cove app  - if someone wants to do a check locally there is no need to install all the web components and other requirements of this web app. The library should be enough.

It's maybe a fair point the readme at https://github.com/open-contracting/lib-cove-oc4ids/blob/master/README.rst could be expanded a bit to help people with this task tho.
