### ISSUE TITLE
Spanish translation

### ISSUE THREAD

**Issue by duncandewhurst** [open-contracting/cove-oc4ids#59]
**Outcome**
A Spanish version of the OC4IDS Data Review Tool available via the version switcher at https://standard.open-contracting.org/infrastructure/review/.

**Outline**
Do the technical work required to enable translation of all text presented to the user in the OC4IDS Data Review Tool, including text from:

* Django templates
* json schema overrides in lib-cove
* lib-cove errors
* the OC4IDS schema

Push strings to Transifex for translation.

Pull translated strings and deploy the Spanish translation to the live site.

**Uncertainties, constraints, assumptions and dependencies**
* Translating the above components should cover all the text in the front-end, but we might find that some text comes from elsewhere.
* Dependency on CDS translating the strings in Transifex

**Client check-points**
@jpmckinney - at what points do you want to check-in on this work?

**Comment by jpmckinney** [comment]
@duncandewhurst I'll be off next week, so don't hold anything up while I'm away. I think the issue is straight-forward (in its description - perhaps not in its implementation!), so I'm happy with just seeing the result.

**Comment by michaelwood** [comment]
I believe we need a transifex project setting up on https://www.transifex.com/open-contracting-partnership-1/public/ for cove-oc4ids . Not sure who can do this? My transifex acc is https://www.transifex.com/user/profile/michaelwood/

**Comment by jpmckinney** [comment]
@michaelwood I've created a cove-oc4ids team, and added you as coordinator, and Ben, Duncan, Rob as managers (like for other teams).

**Comment by michaelwood** [comment]
> @michaelwood I've created a cove-oc4ids team, and added you as coordinator, and Ben, Duncan, Rob as managers (like for other teams).

@jpmckinney  Thanks, from what I understand a "[Project Maintainer](https://docs.transifex.com/teams/understanding-user-roles/)" role/permission is needed to create resources. On the resources page I currently see:

```
No resources to translate yet
Project maintainers have not added any resources
Go back to your Dashboard
```
https://www.transifex.com/open-contracting-partnership-1/cove-oc4ids/content/

(Effectively just need an oc4ids version of the translation resource like the [cove-ocds one](https://www.transifex.com/open-contracting-partnership-1/cove-1/cove-ocds/))

**Comment by jpmckinney** [comment]
@michaelwood You are now Project Maintainer for cove-oc4ids.

**Comment by Bjwebb** [comment]
Today I've been looking at translating strings that come from the `jsonschema` library. These come out of validation functions for each possible key in the json schema file. The list for draft4, which we use, is at https://github.com/Julian/jsonschema/blob/v3.2.0/jsonschema/validators.py#L478-L503

By checking for each of the keys in the OC4IDS schema, I can check where we need to translate strings. (But for OCDS there would be a lot more, as extensions can have arbitrary json schema).

Nothing to do for OC4IDS or OCDS CoVE:
```
No strings in the functions:
        u"$ref": _validators.ref,
        u"properties": _validators.properties,
        u"items": _legacy_validators.items_draft3_draft4,

Already overriden in lib-cove-web:
        u"enum": _validators.enum,
        u"pattern": _validators.pattern,
        u"required": _validators.required,
```

Nothing to do for OC4IDS, but we'd need to check for OCDS:
```
Not in oc4ids schema
        u"additionalItems": _validators.additionalItems,
        u"additionalProperties": _validators.additionalProperties,
        u"allOf": _validators.allOf,
        u"anyOf": _validators.anyOf,
        u"dependencies": _validators.dependencies,
        u"maxItems": _validators.maxItems,
        u"maxLength": _validators.maxLength,
        u"maxProperties": _validators.maxProperties,
        u"maximum": _legacy_validators.maximum_draft3_draft4,
        u"minimum": _legacy_validators.minimum_draft3_draft4,
        u"multipleOf": _validators.multipleOf,
        u"not": _validators.not_,
        u"oneOf": _validators.oneOf,
        u"patternProperties": _validators.patternProperties,

lib-cove-web uri and date-time only
        u"format": _validators.format,

lib-cove-web excludes null and boolean
        u"type": _validators.type,

lib-cove-web for validator_value == 1
        u"minItems": _validators.minItems,
        u"minLength": _validators.minLength,
```

Work to do for OC4IDS:
```
Need adding to lib-cove-web:
        u"minProperties": _validators.minProperties,
        u"uniqueItems": _validators.uniqueItems,
```
