### ISSUE TITLE
Use Django caching for explore pages

### ISSUE THREAD

**Issue by duncandewhurst** [open-contracting/cove-oc4ids#75]
See https://github.com/open-contracting/cove-ocds/issues/90

@jpmckinney requested that this is done as part of the OC4IDS sprint

**Comment by jpmckinney** [comment]
@michaelwood Should we update the deploy repo to install memcached before closing this issue?

**Comment by michaelwood** [comment]
> @michaelwood Should we update the deploy repo to install memcached before closing this issue?

Yes we can do. I wasn't sure if you were going to get the server management folks to do this.

Would you like us to separate out cove-oc4ids into it's own entry in the salt top file or keep the existing config with cove-live* https://github.com/open-contracting/deploy/blob/4daad97231534ebfccebb2c6852a251591cc9157/salt/top.sls#L45 (which would on next deploy also deploy a redundant memcached server to the cove-ocds).  Another option might be to use a flag set in the pillar to make it conditional in the cove.sls but that wouldn't be very neat. After deciding this we will create a  /salt/memcached.sls file to be referenced in the top.sls.

**Comment by jpmckinney** [comment]
I think we can just edit `cove.sls` since the intention is for cove-ocds to also use memcached, so it's okay to have an unused memcached server. (I'm assuming this is just installing the package, but if Memcached is more involved than that, then it can have its own SLS file.)

**Comment by michaelwood** [comment]
Grand, I don't have the required access to push a branch to the `deploy` repo, this is the patch I'm planning on sending:

```diff
diff --git a/salt/cove.sls b/salt/cove.sls
index aac1f26..c3416b7 100644
--- a/salt/cove.sls
+++ b/salt/cove.sls
@@ -28,3 +28,8 @@ MAILTO:
     - name: MAILTO
     - value: sysadmin@open-contracting.org,code@opendataservices.coop
     - user: cove
+
+memcached_server:
+  pkg.installed:
+    - pkgs:
+     - memcached
```
Could you grant me access?

**Comment by jpmckinney** [comment]
@michaelwood I've invited you to the Servers team.
