### ISSUE TITLE
Deploy updated cove-oc4ids

### ISSUE THREAD

**Issue by Bjwebb** [open-contracting/cove-oc4ids#82]
@jpmckinney I think its easier if we do this, so we can redeploy for any fixes needed, but I don't currently have ssh access, could I be added again?

**Comment by jpmckinney** [comment]
@Bjwebb Root access to the CoVE servers has been restored. If Michael wants to deploy, I can add his key as well.

**Comment by jpmckinney** [comment]
As part of this, I ended up deploying both (no failures).

**Comment by Bjwebb** [comment]
Thanks!
