### ISSUE TITLE
Missing spaces in Spanish translation

### ISSUE THREAD

**Issue by duncandewhurst** [open-contracting/cove-oc4ids#92]
@nativaldezt flagged that there are some spaces missing in the Spanish translation ([example](https://standard.open-contracting.org/infrastructure/review/?source_url=https://gist.githubusercontent.com/duncandewhurst/3a607fe8691a18c2a2be2c8bfb36d341/raw/789da49dd8a077ba5e7921b0e579c44d509cc9d8/broken_project.json)):

![image](https://user-images.githubusercontent.com/19265814/116481709-da5e9a00-a8d7-11eb-9cb6-f6892c6feee4.png)

![image](https://user-images.githubusercontent.com/19265814/116481722-e185a800-a8d7-11eb-9b33-1eb5accc075c.png)

![image](https://user-images.githubusercontent.com/19265814/116481728-e64a5c00-a8d7-11eb-8894-83e478c92ad5.png)

**Comment by Bjwebb** [comment]
It should be possible to fix these on Transifex, and then we can do a tx pull. Are they easy enough to find, or I could work out if there's a query we can do to list all of these.

**Comment by duncandewhurst** [comment]
Thanks! Let's tackle this when we next have some OC4IDS dev time scheduled, as I don't think it's urgent.

**Comment by jpmckinney** [comment]
Fixed in https://github.com/OpenDataServices/lib-cove-web/pull/114
