### ISSUE TITLE
Invalid 'uri' found

### ISSUE THREAD

**Issue by aguilerapy** [open-contracting/cove-oc4ids#96]
In [this example](https://standard.open-contracting.org/infrastructure/review/data/aba94036-0c8d-494d-bf18-4fd99fa8d3a2), the tool detects that these URLs (and 20 others) are not valid:

http://www.costjalisco.org.mx/documents/1614983916SIOP-E-ICAR-OB-LP-056-2020_opinióntécnicaambiental.pdf 
http://www.costjalisco.org.mx/documents/1614983995SIOP-E-ICAR-OB-LP-056-2020_anexotécnicodevalidaciónfinanciera.pdf 
http://www.costjalisco.org.mx/documents/1614975463SIOP-E-ICAR-OB-LP-053-2020_opinióntécnicaambiental.pdf 

But they are actually valid, my guess is that words with accents cause this (ó, é).

**Comment by yolile** [comment]
> But they are actually valid

No, they are not. Letters with accents are not allowed in URIs, so they need to encode them. Eg replace http://www.costjalisco.org.mx/documents/1614983916SIOP-E-ICAR-OB-LP-056-2020_opinióntécnicaambiental.pdf with http://www.costjalisco.org.mx/documents/1614983916SIOP-E-ICAR-OB-LP-056-2020_opini%C3%B3nt%C3%A9cnicaambiental.pdf
